routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false
]);

Route::get('lang/{locale}', function ($locale) {
    if (array_key_exists($locale, config('languages'))) {
        session()->put('app_locale', $locale);
    }

    return redirect()->back();
})->name('lang.switch');

Route::get('/redirect', 'Auth\LoginController@redirectToProvider')
    ->name('social_login_redirect');
Route::get('/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'Website\HomeController')->name('home');

Route::get('courses/{course}/details', 'Website\CourseController')
    ->name('course.public.single');

Route::middleware('auth')->group(function () {
    Route::get('dashboard', 'Dashboard\HomeController')->name('dashboard');

    Route::prefix('me')->group(function () {
        Route::get('password/update', 'Dashboard\ProfileController@editPassword')
            ->name('profile.password.edit');

        Route::patch('password/update', 'Dashboard\ProfileController@updatePassword')
            ->name('profile.password.update');

        Route::get('profile/update', 'Dashboard\ProfileController@edit')
            ->name('profile.edit');

        Route::put('profile/update', 'Dashboard\ProfileController@update')
            ->name('profile.update');
    });


    Route::resource('users', 'Dashboard\UserController')
        ->except(['show', 'destroy'])
        ->middleware('can:manage,App\Models\User');

    Route::resource('coupons', 'Dashboard\CouponController')
        ->except(['show'])
        ->middleware('can:manage,App\Models\Coupon');

    Route::prefix('courses/{course}')->group(function () {
        Route::resource('chapters', 'Dashboard\ChapterController')
            ->except(['create', 'edit', 'show']);
        Route::resource('chapters/{chapter}/lessons', 'Dashboard\LessonController')
            ->only(['create', 'edit', 'store', 'update']);
    });

    Route::resource('courses', 'Dashboard\CourseController')
        ->except(['destroy']);

    Route::get('enrollments/pending', 'Dashboard\EnrollmentController@getPending')
        ->name('enrollments.pending');

    Route::post('enrollments/{id}/purchase/approve', 'Dashboard\PurchaseController@approve')
        ->name('enrollments.purchase.approve');

    Route::post('enrollments/{id}/purchase/deny', 'Dashboard\PurchaseController@deny')
        ->name('enrollments.purchase.deny');

    Route::get('enrollments', 'Dashboard\EnrollmentController@index')
        ->name('enrollments.index');

    Route::get('feedbacks/pending', 'Dashboard\FeedbackController@getPending')
        ->name('feedbacks.pending');

    Route::patch('feedbacks/{feedback}/approve', 'Dashboard\FeedbackController@approve')
        ->name('feedbacks.approve');

    Route::get('feedbacks', 'Dashboard\FeedbackController@index')
        ->name('feedbacks.index');

    Route::get('my/courses/ongoing', 'Dashboard\CourseController@getOnGoings')
        ->name('student.courses.ongoing');

    Route::get('my/courses/finished', 'Dashboard\CourseController@getFinished')
        ->name('student.courses.finished');
    
    Route::get('my/courses/{course}', 'Dashboard\CourseController@show')
        ->name('student.course.show');

    Route::prefix('my/courses/{course}')->group(function () {
        Route::post('enroll', 'Dashboard\EnrollmentController@store')
            ->name('student.course.enroll');

        Route::get('lessons/{order?}', 'Dashboard\LessonController@show')
            ->name('student.course.lesson.show');

        Route::get('purchase', 'Dashboard\PurchaseController@create')
            ->name('student.course.purchase.create');

        Route::post('purchase', 'Dashboard\PurchaseController@store')
            ->name('student.course.purchase.store');

        Route::get('purchase-success', 'Dashboard\PurchaseController@getSuccess')
            ->name('student.course.purchase.success');

        Route::get('coupon-check', 'Dashboard\CouponController@check')
            ->name('student.course.coupon.check');
        
        Route::patch('finish', 'Dashboard\EnrollmentController@markFinished')
            ->name('student.course.finish');

        Route::get('feedback', 'Dashboard\FeedbackController@create')
            ->name('student.course.feedback.create');

        Route::post('feedback', 'Dashboard\FeedbackController@store')
            ->name('student.course.feedback.store');

        Route::get('feedback/{feedback}/edit', 'Dashboard\FeedbackController@edit')
            ->name('student.course.feedback.edit');

        Route::put('feedback/{feedback}/update', 'Dashboard\FeedbackController@update')
            ->name('student.course.feedback.update');
    });

    Route::prefix('mail')->group(function () {
        Route::post('enrollment/{enrollment}/approve', 'Dashboard\MailController@sendPurchaseApprove')
            ->name('mail.send.purchase.approve');
        
        Route::post('enrollment/{enrollment}/decline', 'Dashboard\MailController@sendPurchaseDecline')
            ->name('mail.send.purchase.decline');
    });
});

Route::get('storage_link_hidden_url', function () {
    Artisan::call('storage:link');
});

app/Models/Chapter.php
<?php

namespace App\Models;

use App\Traits\TableNameTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Chapter extends Model
{
    use SoftDeletes, TableNameTrait;

    protected $fillable = [
        'title',
        'order',
        'course_id'
    ];

    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function lessons()
    {
        return $this->hasMany(Lesson::class)->orderBy('order');
    }
}

app/Http/Controllers/Dashboard/ChapterController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ChapterRequest;
use App\Models\Chapter;
use App\Models\Course;

class ChapterController extends Controller
{
    public function index(Course $course)
    {
        $this->authorize('manageChapter', $course);

        $chapters = Chapter::with(['lessons'])
            ->where('course_id', $course->id)
            ->orderBy('order', 'asc')
            ->get();

        return view('dashboard.pages.chapter.index', compact('course', 'chapters'));
    }

    public function store(ChapterRequest $request, Course $course)
    {
        $this->authorize('manageChapter', $course);

        Chapter::create($request->validated());

        return redirect()->back()->with('success', 'Chapter created successfully');
    }

    public function update(ChapterRequest $request, Course $course, Chapter $chapter)
    {
        $this->authorize('manageChapter', $course);
        
        $chapter->update($request->validated());

        return redirect()->back()->with('success', 'Chapter edited successfully');
    }
}

resources/views/dashboard/pages/chapter/index.blade.php
@extends('dashboard.layouts.main')

@section('page_title', 'Chapters')

@section('sidebar')
    @include('dashboard.layouts.sidebar')
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @include('dashboard.components.validation-errors')

            <div class="card">
                <div class="card-body">
                    <h4 class="card-title text-center text-primary">{{__('dashboard.course.add_new_chapter')}}</h4>
                    <div class="form-validation">
                        <form class="form-valide" action="{{route('chapters.store', $course)}}" method="post">
                            @csrf
                            
                            <div class="form-group row">
                                <label class="col-lg-2 col-form-label text-right">Title <span class="text-danger">*</span>
                                </label>
                                <div class="col-lg-10">
                                    <input type="text" class="form-control" name="title" value="{{old('title')}}" placeholder="Enter a Title.." required>
                                </div>
                            </div>

                            <input type="hidden" name="course_id" value="{{$course->id}}">
                            <input type="hidden" name="order" value="{{$chapters->count() + 1}}">

                            <div class="form-group row text-center">
                                <div class="col-lg-12 ml-auto">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @foreach ($chapters as $chapter)
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header bg-white">
                        <div class="accordion">
                            <div class="card">
                                <div class="card-header">
                                    <h5 class="mb-0" data-toggle="collapse" data-target="#chapter{{$chapter->id}}" aria-expanded="true" aria-controls="chapter{{$chapter->id}}"><i class="fa fa-edit pull-right" aria-hidden="true"></i> {{$chapter->title}}</h5>
                                </div>
                                <div id="chapter{{$chapter->id}}" class="collapse">
                                    <div class="card-body">
                                        <div class="form-validation">
                                            <form class="form-valide" action="{{route('chapters.update', [$course, $chapter])}}" method="post">
                                                @csrf
                                                @method('PUT')
                                                
                                                <div class="form-group row">
                                                    <label class="col-lg-2 col-form-label text-right">Title <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-10">
                                                        <input type="text" class="form-control" name="title" value="{{old('title', $chapter->title)}}" placeholder="Enter a Title.." required>
                                                    </div>
                                                </div>
                    
                                                <input type="hidden" name="course_id" value="{{$course->id}}">
                                                <input type="hidden" name="order" value="{{$chapter->order}}">
                    
                                                <div class="form-group row text-center">
                                                    <div class="col-lg-12 ml-auto">
                                                        <button type="submit" class="btn btn-success">Update</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="basic-list-group">
                            <ul class="list-group">
                                @foreach ($chapter->lessons as $lesson)
                                <li class="list-group-item d-flex justify-content-between align-items-center">{{$lesson->title}} 
                                    <span class="">
                                        <a href="{{route('lessons.edit', [$course, $chapter, $lesson])}}" class="pull-right"><i class="fa fa-edit"></i></a>
                                    </span>
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group row text-center">
                            <div class="col-lg-12 ml-auto">
                                <a href="{{route('lessons.create', [$course, $chapter])}}" class="btn btn-primary">Add New Lesson</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
@endsection