routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false
]);

Route::get('lang/{locale}', function ($locale) {
    if (array_key_exists($locale, config('languages'))) {
        session()->put('app_locale', $locale);
    }

    return redirect()->back();
})->name('lang.switch');

Route::get('/redirect', 'Auth\LoginController@redirectToProvider')
    ->name('social_login_redirect');
Route::get('/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'Website\HomeController')->name('home');

Route::get('courses/{course}/details', 'Website\CourseController')
    ->name('course.public.single');

Route::middleware('auth')->group(function () {
    Route::get('dashboard', 'Dashboard\HomeController')->name('dashboard');

    Route::prefix('me')->group(function () {
        Route::get('password/update', 'Dashboard\ProfileController@editPassword')
            ->name('profile.password.edit');

        Route::patch('password/update', 'Dashboard\ProfileController@updatePassword')
            ->name('profile.password.update');

        Route::get('profile/update', 'Dashboard\ProfileController@edit')
            ->name('profile.edit');

        Route::put('profile/update', 'Dashboard\ProfileController@update')
            ->name('profile.update');
    });


    Route::resource('users', 'Dashboard\UserController')
        ->except(['show', 'destroy'])
        ->middleware('can:manage,App\Models\User');

    Route::resource('coupons', 'Dashboard\CouponController')
        ->except(['show'])
        ->middleware('can:manage,App\Models\Coupon');

    Route::prefix('courses/{course}')->group(function () {
        Route::resource('chapters', 'Dashboard\ChapterController')
            ->except(['create', 'edit', 'show']);
        Route::resource('chapters/{chapter}/lessons', 'Dashboard\LessonController')
            ->only(['create', 'edit', 'store', 'update']);
    });

    Route::resource('courses', 'Dashboard\CourseController')
        ->except(['destroy']);

    Route::get('enrollments/pending', 'Dashboard\EnrollmentController@getPending')
        ->name('enrollments.pending');

    Route::post('enrollments/{id}/purchase/approve', 'Dashboard\PurchaseController@approve')
        ->name('enrollments.purchase.approve');

    Route::post('enrollments/{id}/purchase/deny', 'Dashboard\PurchaseController@deny')
        ->name('enrollments.purchase.deny');

    Route::get('enrollments', 'Dashboard\EnrollmentController@index')
        ->name('enrollments.index');

    Route::get('feedbacks/pending', 'Dashboard\FeedbackController@getPending')
        ->name('feedbacks.pending');

    Route::patch('feedbacks/{feedback}/approve', 'Dashboard\FeedbackController@approve')
        ->name('feedbacks.approve');

    Route::get('feedbacks', 'Dashboard\FeedbackController@index')
        ->name('feedbacks.index');

    Route::get('my/courses/ongoing', 'Dashboard\CourseController@getOnGoings')
        ->name('student.courses.ongoing');

    Route::get('my/courses/finished', 'Dashboard\CourseController@getFinished')
        ->name('student.courses.finished');
    
    Route::get('my/courses/{course}', 'Dashboard\CourseController@show')
        ->name('student.course.show');

    Route::prefix('my/courses/{course}')->group(function () {
        Route::post('enroll', 'Dashboard\EnrollmentController@store')
            ->name('student.course.enroll');

        Route::get('lessons/{order?}', 'Dashboard\LessonController@show')
            ->name('student.course.lesson.show');

        Route::get('purchase', 'Dashboard\PurchaseController@create')
            ->name('student.course.purchase.create');

        Route::post('purchase', 'Dashboard\PurchaseController@store')
            ->name('student.course.purchase.store');

        Route::get('purchase-success', 'Dashboard\PurchaseController@getSuccess')
            ->name('student.course.purchase.success');

        Route::get('coupon-check', 'Dashboard\CouponController@check')
            ->name('student.course.coupon.check');
        
        Route::patch('finish', 'Dashboard\EnrollmentController@markFinished')
            ->name('student.course.finish');

        Route::get('feedback', 'Dashboard\FeedbackController@create')
            ->name('student.course.feedback.create');

        Route::post('feedback', 'Dashboard\FeedbackController@store')
            ->name('student.course.feedback.store');

        Route::get('feedback/{feedback}/edit', 'Dashboard\FeedbackController@edit')
            ->name('student.course.feedback.edit');

        Route::put('feedback/{feedback}/update', 'Dashboard\FeedbackController@update')
            ->name('student.course.feedback.update');
    });

    Route::prefix('mail')->group(function () {
        Route::post('enrollment/{enrollment}/approve', 'Dashboard\MailController@sendPurchaseApprove')
            ->name('mail.send.purchase.approve');
        
        Route::post('enrollment/{enrollment}/decline', 'Dashboard\MailController@sendPurchaseDecline')
            ->name('mail.send.purchase.decline');
    });
});

Route::get('storage_link_hidden_url', function () {
    Artisan::call('storage:link');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class User extends Authenticatable implements HasMedia
{
    use Notifiable, SoftDeletes, InteractsWithMedia;

    public const PAGINATION_LENGTH = 20;

    public const ROLE_ADMIN = 'admin';
    public const ROLE_INSTRUCTOR = 'instructor';
    public const ROLE_STUDENT = 'student';

    public const ROLES = [
        self::ROLE_ADMIN,
        self::ROLE_INSTRUCTOR,
        self::ROLE_STUDENT
    ];

    public const AUTH_GOOGLE_CLIENT = 'google';

    public const DEFAULT_USER_AVATAR_IMAGE_PATH = 'assets/common/images/user_placeholder.png';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'bn_name',
        'email',
        'password',
        'email_verified_at',
        'designation',
        'bn_designation',
        'description',
        'bn_description',
        'role',
        'image',
        'github_url',
        'linkedin_url',
        'facebook_url',
        'oauth_id',
        'oauth_client'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function enrollments()
    {
        return $this->hasMany(Enrollment::class);
    }

    /**
     * Scope a query to only include users with role 'admin'.
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeAdmins(Builder $query)
    {
        return $query->where('role', self::ROLE_ADMIN);
    }

    /**
     * Scope a query to only include users with role 'instructor'.
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeInstructors(Builder $query)
    {
        return $query->where('role', self::ROLE_INSTRUCTOR);
    }

    /**
     * Scope a query to only include users with role 'student'.
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeStudents(Builder $query)
    {
        return $query->where('role', self::ROLE_STUDENT);
    }

    public function registerMediaConversions(?Media $meda = null): void
    {
        $this->addMediaConversion('thumb')
              ->width(100)
              ->height(100)
              ->sharpen(10)
              ->keepOriginalImageFormat();
    }

    public function getName(): ?string
    {
        if (app()->isLocale('bn') && !empty($this->bn_name)) {
            return $this->bn_name;
        }

        return $this->name;
    }

    public function getDesignation(): ?string
    {
        if (app()->isLocale('bn') && !empty($this->bn_designation)) {
            return $this->bn_designation;
        }

        return $this->designation;
    }

    public function getDescription(): ?string
    {
        if (app()->isLocale('bn') && !empty($this->bn_description)) {
            return $this->bn_description;
        }

        return $this->description;
    }

    public function getProfileImagePath()
    {
        if ($this->isOAuthUser($this)) {
            return $this->image;
        }

        return asset(
            $this->getFirstMedia()
                ? $this->getFirstMediaUrl('default', 'thumb')
                : self::DEFAULT_USER_AVATAR_IMAGE_PATH
        );
    }

    private function isOAuthUser(User $user): bool
    {
        return $user->oauth_client !== null;
    }

    public function isStudent(): bool
    {
        return $this->role === self::ROLE_STUDENT;
    }

    public function isInstructor(): bool
    {
        return $this->role === self::ROLE_INSTRUCTOR;
    }

    public function isAdmin(): bool
    {
        return $this->role === self::ROLE_ADMIN;
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        $users = User::paginate(User::PAGINATION_LENGTH);
        
        return view('dashboard.pages.user.index', compact('users'));
    }

    public function create()
    {
        return view('dashboard.pages.user.create');
    }

    public function store(CreateUserRequest $request)
    {
        $data = $request->validated();
        $data['password'] = Hash::make($data['password']);

        User::create($data);

        return redirect()->back()
            ->with('success', 'User created successfully');
    }

    public function edit(User $user)
    {
        return view('dashboard.pages.user.edit', compact('user'));
    }

    public function update(UpdateUserRequest $request, User $user)
    {
        $data = $request->validated();

        if (!empty($data['password'])) {
            $data['password'] = Hash::make($data['password']);
        } else {
            unset($data['password']);
        }

        $user->update($data);

        return redirect()->back()
            ->with('success', 'User updated successfully');
    }
}

resources/views/dashboard/pages/user/create.blade.php
@extends('dashboard.layouts.main')

@section('page_title', 'User create')

@section('sidebar')
    @include('dashboard.layouts.sidebar')
@endsection

@section('content')
    <div class="col-lg-12">
        @include('dashboard.components.validation-errors')

        <div class="card">
            <div class="card-header">
                <h4 class="text-center">{{__('dashboard.user.create')}}</h4>
            </div>
            <div class="card-body">
                <div class="form-validation">
                    <form class="form-valide" action="{{route('users.store')}}" method="post">
                        @csrf
                        
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Name <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <input type="text" class="form-control" name="name" value="{{old('name')}}" placeholder="Enter a Name.." required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Email <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <input type="text" class="form-control" name="email" value="{{old('email')}}" placeholder="Enter an Email.." required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Role <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <select class="form-control" name="role">
                                    <option {{ (old('role') === App\Models\User::ROLE_INSTRUCTOR) ? 'selected' : '' }} value="{{App\Models\User::ROLE_INSTRUCTOR}}">{{ucfirst(App\Models\User::ROLE_INSTRUCTOR)}}</option>
                                    <option {{ (old('role') === App\Models\User::ROLE_ADMIN) ? 'selected' : '' }} value="{{App\Models\User::ROLE_ADMIN}}">{{ucfirst(App\Models\User::ROLE_ADMIN)}}</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Password <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <input type="password" class="form-control" name="password" value="{{old('password')}}" placeholder="Enter a Password.." required>
                            </div>
                        </div>

                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-success">{{__('dashboard.buttons.submit')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/pages/user/edit.blade.php
@extends('dashboard.layouts.main')

@section('page_title', 'User Edit')

@section('sidebar')
    @include('dashboard.layouts.sidebar')
@endsection

@section('content')
    <div class="col-lg-12">
        @include('dashboard.components.validation-errors')

        <div class="card">
            <div class="card-header">
                <h4 class="text-center">{{__('dashboard.user.update')}}</h4>
            </div>
            <div class="card-body">
                <div class="form-validation">
                    <form class="form-valide" action="{{route('users.update', $user)}}" method="post">
                        @csrf
                        @method('PUT')
                        
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Name <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <input type="text" class="form-control" name="name" value="{{old('name', $user->name)}}" placeholder="Enter a Name.." required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Email <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <input type="text" class="form-control" name="email" value="{{old('email', $user->email)}}" placeholder="Enter an Email.." required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Role <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <select class="form-control" name="role">
                                    <option {{ (old('role', $user->role) === App\Models\User::ROLE_INSTRUCTOR) ? 'selected' : '' }} value="{{App\Models\User::ROLE_INSTRUCTOR}}">{{ucfirst(App\Models\User::ROLE_INSTRUCTOR)}}</option>
                                    <option {{ (old('role', $user->role) === App\Models\User::ROLE_ADMIN) ? 'selected' : '' }} value="{{App\Models\User::ROLE_ADMIN}}">{{ucfirst(App\Models\User::ROLE_ADMIN)}}</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Password
                            </label>
                            <div class="col-lg-6">
                                <input type="password" class="form-control" name="password" value="{{old('password')}}" placeholder="Enter updated Password..">
                            </div>
                        </div>

                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-success">{{__('dashboard.buttons.submit')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/pages/user/index.blade.php
@extends('dashboard.layouts.main')

@section('page_title', 'Users List')

@section('sidebar')
    @include('dashboard.layouts.sidebar')
@endsection

@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title pull-left">{{__('dashboard.user.list')}}</h4>
                <a class="pull-right btn btn-info" href="{{ route('users.create') }}">Create New User</a>
                <div class="table-responsive mt-5">
                    <table class="table table-bordered table-striped verticle-middle">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Designation</th>
                            <th scope="col">Role</th>
                            <th scope="col">Edit</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{$user->designation}}</td>
                                <td>{{$user->role}}</td>
                                <td class="text-center">
                                    <span><a href="{{ route('users.edit', $user)}}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><i class="fa fa-pencil color-muted m-r-5"></i></a></span>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $users->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection