routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false
]);

Route::get('lang/{locale}', function ($locale) {
    if (array_key_exists($locale, config('languages'))) {
        session()->put('app_locale', $locale);
    }

    return redirect()->back();
})->name('lang.switch');

Route::get('/redirect', 'Auth\LoginController@redirectToProvider')
    ->name('social_login_redirect');
Route::get('/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'Website\HomeController')->name('home');

Route::get('courses/{course}/details', 'Website\CourseController')
    ->name('course.public.single');

Route::middleware('auth')->group(function () {
    Route::get('dashboard', 'Dashboard\HomeController')->name('dashboard');

    Route::prefix('me')->group(function () {
        Route::get('password/update', 'Dashboard\ProfileController@editPassword')
            ->name('profile.password.edit');

        Route::patch('password/update', 'Dashboard\ProfileController@updatePassword')
            ->name('profile.password.update');

        Route::get('profile/update', 'Dashboard\ProfileController@edit')
            ->name('profile.edit');

        Route::put('profile/update', 'Dashboard\ProfileController@update')
            ->name('profile.update');
    });


    Route::resource('users', 'Dashboard\UserController')
        ->except(['show', 'destroy'])
        ->middleware('can:manage,App\Models\User');

    Route::resource('coupons', 'Dashboard\CouponController')
        ->except(['show'])
        ->middleware('can:manage,App\Models\Coupon');

    Route::prefix('courses/{course}')->group(function () {
        Route::resource('chapters', 'Dashboard\ChapterController')
            ->except(['create', 'edit', 'show']);
        Route::resource('chapters/{chapter}/lessons', 'Dashboard\LessonController')
            ->only(['create', 'edit', 'store', 'update']);
    });

    Route::resource('courses', 'Dashboard\CourseController')
        ->except(['destroy']);

    Route::get('enrollments/pending', 'Dashboard\EnrollmentController@getPending')
        ->name('enrollments.pending');

    Route::post('enrollments/{id}/purchase/approve', 'Dashboard\PurchaseController@approve')
        ->name('enrollments.purchase.approve');

    Route::post('enrollments/{id}/purchase/deny', 'Dashboard\PurchaseController@deny')
        ->name('enrollments.purchase.deny');

    Route::get('enrollments', 'Dashboard\EnrollmentController@index')
        ->name('enrollments.index');

    Route::get('feedbacks/pending', 'Dashboard\FeedbackController@getPending')
        ->name('feedbacks.pending');

    Route::patch('feedbacks/{feedback}/approve', 'Dashboard\FeedbackController@approve')
        ->name('feedbacks.approve');

    Route::get('feedbacks', 'Dashboard\FeedbackController@index')
        ->name('feedbacks.index');

    Route::get('my/courses/ongoing', 'Dashboard\CourseController@getOnGoings')
        ->name('student.courses.ongoing');

    Route::get('my/courses/finished', 'Dashboard\CourseController@getFinished')
        ->name('student.courses.finished');
    
    Route::get('my/courses/{course}', 'Dashboard\CourseController@show')
        ->name('student.course.show');

    Route::prefix('my/courses/{course}')->group(function () {
        Route::post('enroll', 'Dashboard\EnrollmentController@store')
            ->name('student.course.enroll');

        Route::get('lessons/{order?}', 'Dashboard\LessonController@show')
            ->name('student.course.lesson.show');

        Route::get('purchase', 'Dashboard\PurchaseController@create')
            ->name('student.course.purchase.create');

        Route::post('purchase', 'Dashboard\PurchaseController@store')
            ->name('student.course.purchase.store');

        Route::get('purchase-success', 'Dashboard\PurchaseController@getSuccess')
            ->name('student.course.purchase.success');

        Route::get('coupon-check', 'Dashboard\CouponController@check')
            ->name('student.course.coupon.check');
        
        Route::patch('finish', 'Dashboard\EnrollmentController@markFinished')
            ->name('student.course.finish');

        Route::get('feedback', 'Dashboard\FeedbackController@create')
            ->name('student.course.feedback.create');

        Route::post('feedback', 'Dashboard\FeedbackController@store')
            ->name('student.course.feedback.store');

        Route::get('feedback/{feedback}/edit', 'Dashboard\FeedbackController@edit')
            ->name('student.course.feedback.edit');

        Route::put('feedback/{feedback}/update', 'Dashboard\FeedbackController@update')
            ->name('student.course.feedback.update');
    });

    Route::prefix('mail')->group(function () {
        Route::post('enrollment/{enrollment}/approve', 'Dashboard\MailController@sendPurchaseApprove')
            ->name('mail.send.purchase.approve');
        
        Route::post('enrollment/{enrollment}/decline', 'Dashboard\MailController@sendPurchaseDecline')
            ->name('mail.send.purchase.decline');
    });
});

Route::get('storage_link_hidden_url', function () {
    Artisan::call('storage:link');
});

app/Models/Course.php
<?php

namespace App\Models;

use App\Traits\TableNameTrait;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Course extends Model implements HasMedia
{
    use SoftDeletes, TableNameTrait, InteractsWithMedia;

    public const TYPE_FREE = 'free';
    public const TYPE_PREMIUM = 'premium';

    public const TYPES = [
        self::TYPE_FREE,
        self::TYPE_PREMIUM
    ];

    public const STATUS_AVAILABLE = 'available';
    public const STATUS_UPCOMING = 'upcoming';
    public const STATUS_UNAVAILABLE = 'unavailable';

    public const STATUSES = [
        self::STATUS_AVAILABLE,
        self::STATUS_UNAVAILABLE,
        self::STATUS_UPCOMING
    ];

    public const STATUS_COLOR = [
        self::STATUS_AVAILABLE => 'success',
        self::STATUS_UPCOMING => 'warning',
        self::STATUS_UNAVAILABLE => 'danger'
    ];

    protected $fillable = [
        'title',
        'slug',
        'type',
        'status',
        'fee',
        'discount',
        'instructor_id',
        'public_description',
        'bn_public_description',
        'private_description',
        'bn_private_description',
        'number_of_lessons',
        'estimated_completion_time'
    ];

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function instructor()
    {
        return $this->belongsTo(User::class);
    }

    public function chapters()
    {
        return $this->hasMany(Chapter::class)->orderBy('order');
    }

    public function feedbacks()
    {
        return $this->hasMany(Feedback::class)->orderBy('rating', 'desc');
    }

    public function enrollments()
    {
        return $this->hasMany(Enrollment::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * Scope a query to only include courses which are 'free'.
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeFreebies(Builder $query)
    {
        return $query->where('type', self::TYPE_FREE);
    }

    /**
     * Scope a query to only include courses which are 'free'.
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopePremiums(Builder $query)
    {
        return $query->where('type', self::TYPE_PREMIUM);
    }

    /**
     * Scope a query to only include courses which are 'available'.
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeAvailables(Builder $query)
    {
        return $query->where('status', self::STATUS_AVAILABLE);
    }

    /**
     * Scope a query to only include courses which are 'upcoming'.
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeUpcomings(Builder $query)
    {
        return $query->where('status', self::STATUS_UPCOMING);
    }

    /**
     * Scope a query to only include courses which are 'unavailable'.
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeUnavailables(Builder $query)
    {
        return $query->where('status', self::STATUS_UNAVAILABLE);
    }

    /**
     * Scope a query to only include courses which are 'unavailable'.
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeExceptUnavailables(Builder $query)
    {
        return $query->where('status', '<>', self::STATUS_UNAVAILABLE);
    }

    public function registerMediaConversions(?Media $meda = null): void
    {
        $this->addMediaConversion('thumb')
              ->width(540)
              ->height(304)
              ->sharpen(10)
              ->keepOriginalImageFormat();
    }

    public function getPublicDescription(): ?string
    {
        if (app()->isLocale('bn') && !empty($this->bn_public_description)) {
            return $this->bn_public_description;
        }

        return $this->public_description;
    }

    public function getPrivateDescription(): ?string
    {
        if (app()->isLocale('bn') && !empty($this->bn_private_description)) {
            return $this->bn_private_description;
        }

        return $this->private_description;
    }

    public function getBannerImagePath(): string
    {
        $placeholderImage = 'assets/common/images/course_placeholder.jpg';

        return $this->getFirstMedia()
            ? $this->getFirstMediaUrl('default', 'thumb')
            : $placeholderImage;
    }

    public function getStatusColor()
    {
        return self::STATUS_COLOR[$this->status] ?? 'primary';
    }

    public function getFee()
    {
        return $this->type === Course::TYPE_FREE ? 'Free' : $this->fee;
    }

    public function getDiscountedFee()
    {
        return $this->type === Course::TYPE_FREE ? 'Free' : ($this->fee - $this->discount);
    }

    public function hasDiscount(): bool
    {
        if ((int)$this->discount > 0) {
            return true;
        }

        return false;
    }

    public function isAvailable(): bool
    {
        return $this->status === self::STATUS_AVAILABLE;
    }

    public function isUnAvailable(): bool
    {
        return $this->status === self::STATUS_UNAVAILABLE;
    }

    public function isNotAvailable(): bool
    {
        return !$this->isAvailable();
    }

    public function isFree(): bool
    {
        return $this->type === self::TYPE_FREE;
    }

    public function getBkashNumber(): string
    {
        return '01921099556';
    }
}

app/Http/Controllers/Dashboard/CourseController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Exception;
use App\Models\User;
use App\Models\Course;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateCourseRequest;
use App\Http\Requests\UpdateCourseRequest;
use App\Http\Services\EnrollmentService;
use App\Http\Services\CourseService;
use App\Models\Feedback;
use App\Policies\FeedbackPolicy;
use Illuminate\View\View;

class CourseController extends Controller
{
    /** @var CourseService */
    private $courseService;

    /** @var EnrollmentService */
    private $enrollmentService;

    public function __construct(CourseService $courseService, EnrollmentService $enrollmentService)
    {
        $this->courseService = $courseService;
        $this->enrollmentService = $enrollmentService;
    }

    public function create()
    {
        $this->authorize('create', Course::class);

        return view('dashboard.pages.course.create');
    }

    public function store(CreateCourseRequest $request)
    {
        $this->authorize('create', Course::class);

        $this->courseService->create($request->validated());

        return redirect()->back()->with('success', 'Course created successfully');
    }

    public function edit(Course $course)
    {
        $this->authorize('update', $course);

        return view('dashboard.pages.course.edit', compact('course'));
    }

    public function update(UpdateCourseRequest $request, Course $course)
    {
        $this->authorize('update', $course);

        $this->courseService->update($course, $request->validated());

        return redirect()->back()->with('success', 'Course edited successfully');
    }

    public function index()
    {
        $this->authorize('viewAny', Course::class);

        $courses = [];
        
        /** @var User $loggedInUser */
        $loggedInUser = auth()->user();

        if ($loggedInUser->isAdmin()) {
            $courses = $this->courseService->getAllForAdmin();
        } elseif ($loggedInUser->isInstructor()) {
            $courses = $this->courseService->getAllForInstructor(auth()->user()->id);
        }

        return view('dashboard.pages.course.index', compact('courses'));
    }

    public function show(Course $course)
    {
        $course->load(['instructor', 'chapters.lessons']);
        
        try {
            $enrollment = null;
            $feedback = null;

            /** @var User $loggedInUser */
            $loggedInUser = auth()->user();

            if ($loggedInUser->isStudent()) {
                $enrollment = $this->enrollmentService->getEnrollment(
                    $course->id,
                    auth()->user()->id,
                    ['course']
                );
                $feedback = Feedback::where('user_id', auth()->user()->id)
                    ->where('course_id', $course->id)
                    ->first();
            }

            $this->authorize('view', [$course, $enrollment]);
        } catch (Exception $e) {
            return redirect()->to('dashboard')->with('error', $e->getMessage());
        }

        return view('dashboard.pages.course.home', compact('course', 'enrollment', 'feedback'));
    }

    public function getOnGoings(): View
    {
        $this->authorize('viewOnGoing', Course::class);

        $onGoingCourses = $this->courseService->getOngoingCoursesForStudent(auth()->user()->id);

        return view('dashboard.pages.course.ongoing', compact('onGoingCourses'));
    }

    public function getFinished(): View
    {
        $this->authorize('viewFinished', Course::class);

        $finishedCourses = $this->courseService->getFinishedCoursesForStudent(auth()->user()->id);

        return view('dashboard.pages.course.finished', compact('finishedCourses'));
    }
}

app/Http/Controllers/Website/CourseController.php
<?php

namespace App\Http\Controllers\Website;

use Exception;
use App\Models\Course;
use Illuminate\View\View;
use Illuminate\Contracts\View\Factory;

class CourseController
{
    /**
     * @param Course $course
     * @return Factory|View
     * @throws Exception
     */
    public function __invoke(Course $course)
    {
        if ($course->isUnAvailable()) {
            return redirect('home')
                ->with('error', 'Sorry, the course is not available');
        }

        $course->load(['instructor', 'feedbacks.user', 'chapters.lessons']);
        return view('website.course-details')->with('course', $course);
    }
}

resources/views/dashboard/pages/course/create.blade.php
@extends('dashboard.layouts.main')

@section('page_title', 'Course create')

@section('sidebar')
    @include('dashboard.layouts.sidebar')
@endsection

@section('content')
    <div class="col-lg-12">
        @include('dashboard.components.validation-errors')

        <div class="card">
            <div class="card-header">
                <h4 class="text-center">{{__('dashboard.course.create_course')}}</h4>
            </div>
            <div class="card-body">
                <div class="form-validation">
                    <form class="form-valide" action="{{route('courses.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Title <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <input type="text" class="form-control" name="title" value="{{old('title')}}" placeholder="Enter a Title.." required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Type <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <select class="form-control" name="type">
                                    @foreach(\App\Models\Course::TYPES as $type)
                                    <option {{ (old('type') === $type) ? 'selected' : '' }} value="{{$type}}">{{ucfirst($type)}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Status <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <select class="form-control" name="status">
                                    @foreach(\App\Models\Course::STATUSES as $status)
                                        <option {{ (old('status') === $status) ? 'selected' : '' }} value="{{$status}}">{{$status}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Course Fee <span class="text-danger">*</span>
                            </label>
                            <div class="col-lg-6">
                                <input type="number" class="form-control" name="fee" value="{{old('fee', 0)}}" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Discount
                            </label>
                            <div class="col-lg-6">
                                <input type="number" class="form-control" name="discount" value="{{old('discount', 0)}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label">Estimated completion time (in minute)
                            </label>
                            <div class="col-lg-6">
                                <input type="text" class="form-control" name="estimated_completion_time" value="{{old('estimated_completion_time')}}" placeholder="Estimated Completion time">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label" for="public_description">Public Description
                            </label>
                            <div class="col-lg-6">
                                <textarea class="form-control" id="public_description" name="public_description" rows="5" placeholder="Public Description">{{old('public_description')}}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label" for="bn_public_description">Bangla Public Description
                            </label>
                            <div class="col-lg-6">
                                <textarea class="form-control" id="bn_public_description" name="bn_public_description" rows="5" placeholder="Bangla Public Description">{{old('bn_public_description')}}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label" for="private_description">Private Description
                            </label>
                            <div class="col-lg-6">
                                <textarea class="form-control" id="private_description" name="private_description" rows="5" placeholder="Private Description">{{old('private_description')}}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label" for="bn_private_description">Bangla Private Description
                            </label>
                            <div class="col-lg-6">
                                <textarea class="form-control" id="bn_private_description" name="bn_private_description" rows="5" placeholder="Bangla Private Description">{{old('bn_private_description')}}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-4 col-form-label" for="image">Banner Image
                            </label>
                            <div class="col-lg-6">
                                <input type="file" id="image" name="image" class="form-control-file">
                            </div>
                        </div>

                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-success">{{__('dashboard.buttons.submit')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/pages/course/finished.blade.php
@extends('dashboard.layouts.main')

@section('page_title', 'Finished Courses')

@section('sidebar')
    @include('dashboard.layouts.sidebar')
@endsection

@section('content')
    @if($finishedCourses->isEmpty())
        @include('dashboard.components.empty-finished-courses')
    @else
        @include('dashboard.components.finished-courses-component')
    @endif
@endsection

resources/views/dashboard/pages/course/home.blade.php
@extends('dashboard.layouts.main')

@section('page_title', 'Course - ' . $course->title)

@section('sidebar')
    @include('dashboard.layouts.course-contents-sidebar')
@endsection

@section('breadcrumb')
    @include('dashboard.components.course-contents-breadcrumb')
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12 col-sm-12">
            <div class="card gradient-1">
                <div class="card-body text-center">
                    <h3 class="card-title text-white">{{__('dashboard.course.welcome')}}</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">{{$course->title}}</h2>
                        <p class="text-white mb-0"><strong>{{__('dashboard.course.number_of_lessons')}}:</strong> {{$course->number_of_lessons}}</p>
                        @if($course->estimated_completion_time)
                        <p class="text-white mb-0"><strong>{{__('dashboard.course.completion_time')}}:
                            </strong> {{ App\Extensions\Formatter::toHourMinuteString($course->estimated_completion_time)}}
                        </p>
                        @endif

                        @if ($course->number_of_lessons > 0)
                            <a href="{{route('student.course.lesson.show', $course)}}" class="btn mb-1 btn-success mt-4">
                                {{__('dashboard.course.lets_explore')}} <span class="btn-icon-right"><i class="icon-book-open"></i></span>
                            </a>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-8 col-sm-8">
            <div class="card">
                <div class="card-body">
                    <div class="d-inline-block">
                        <h5>{{__('dashboard.course.description')}}</h5>
                        <p>{!! nl2br(e($course->getPublicDescription())) !!}</p>
                    </div>
                </div>
            </div>

            @if(!empty($course->getPrivateDescription()))
            <div class="card">
                <div class="card-body">
                    <div class="d-inline-block">
                        <h5>{{__('dashboard.course.private_note')}}</h5>
                        <p>{!! nl2br(e($course->getPrivateDescription())) !!}</p>
                    </div>
                </div>
            </div>
            @endif
        </div>

        <div class="col-lg-4 col-sm-4">
            <div class="card">
                <div class="card-header text-center text-primary font-weight-bold">
                    {{__('dashboard.course.instructor')}}
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img src="{{$course->instructor->getProfileImagePath()}}" style="width: 80px;"  class="rounded-circle" alt="">
                        <h5 class="mt-3 mb-1">{{$course->instructor->getName()}}</h5>
                        <p class="m-0">{{$course->instructor->getDesignation()}}</p>
                    </div>
                    <div class="mt-3">
                        <h4>{{__('dashboard.course.about')}}</h4>
                        <p class="text-muted">{!! nl2br(e($course->instructor->getDescription())) !!}</p>
                    </div>
                </div>
            </div>

            @if(auth()->user()->isStudent() && $feedback)
            <div class="card">
                <div class="card-header text-center text-primary font-weight-bold">
                    {{__('dashboard.course.your_feedback')}}
                </div>
                <div class="card-body">
                    <div class="mt-3">
                        @include('common.feedback_stars')
                        
                        <p class="text-muted">{{$feedback->description}}</p>
                        <div class="d-flex justify-content-center">
                            <a href="{{route('student.course.feedback.edit', [$course, $feedback])}}" class="btn btn-warning">{{__('dashboard.course.edit_feedback')}}</a>
                        </div>
                    </div>
                </div>
            </div>
            @endif

        </div>
    </div>
@endsection

resources/views/dashboard/pages/course/index.blade.php
@extends('dashboard.layouts.main')

@section('page_title', 'Course List')

@section('sidebar')
    @include('dashboard.layouts.sidebar')
@endsection

@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title pull-left">{{__('dashboard.course.course_list')}}</h4>
                <a class="pull-right btn btn-info" href="{{ route('courses.create') }}">Create New Course</a>
                <div class="table-responsive mt-5">
                    <table class="table table-bordered table-striped verticle-middle">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Course Title</th>
                            <th scope="col">Instructor</th>
                            <th scope="col">Course Type</th>
                            <th scope="col">Course Status</th>
                            <th scope="col">Course Fee</th>
                            <th scope="col">Discount</th>
                            <th scope="col">Total Lessons</th>
                            <th scope="col">Total Enrollment</th>
                            <th scope="col">Manage Chapters</th>
                            <th scope="col">Edit</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($courses as $course)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td><a class="text-primary" href="{{route('courses.show', $course)}}" >{{$course->title}}</a></td>
                                <td>{{$course->instructor->name}}</td>
                                <td>{{$course->type}}</td>
                                <td class="text-{{$course->getStatusColor()}}">{{$course->status}}</td>
                                <td>{{$course->getFee()}}</td>
                                <td>{{$course->discount}}</td>
                                <td>{{$course->number_of_lessons}}</td>
                                <td>{{$course->enrollments->count()}}</td>
                                <td class="text-center">
                                    <span><a href="{{ route('chapters.index', $course)}}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Manage Chapters"><i class="fa fa-book color-muted m-r-5"></i></a></span>
                                </td>
                                <td class="text-center">
                                    <span><a href="{{ route('courses.edit', $course)}}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><i class="fa fa-pencil color-muted m-r-5"></i></a></span>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/pages/course/ongoing.blade.php
@extends('dashboard.layouts.main')

@section('page_title', 'Ongoing Courses')

@section('sidebar')
    @include('dashboard.layouts.sidebar')
@endsection

@section('content')
    @if($onGoingCourses->isEmpty())
        @include('dashboard.components.empty-ongoing-courses')
    @else
        @include('dashboard.components.ongoing-courses-component')
    @endif
@endsection