routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false
]);

Route::get('lang/{locale}', function ($locale) {
    if (array_key_exists($locale, config('languages'))) {
        session()->put('app_locale', $locale);
    }

    return redirect()->back();
})->name('lang.switch');

Route::get('/redirect', 'Auth\LoginController@redirectToProvider')
    ->name('social_login_redirect');
Route::get('/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'Website\HomeController')->name('home');

Route::get('courses/{course}/details', 'Website\CourseController')
    ->name('course.public.single');

Route::middleware('auth')->group(function () {
    Route::get('dashboard', 'Dashboard\HomeController')->name('dashboard');

    Route::prefix('me')->group(function () {
        Route::get('password/update', 'Dashboard\ProfileController@editPassword')
            ->name('profile.password.edit');

        Route::patch('password/update', 'Dashboard\ProfileController@updatePassword')
            ->name('profile.password.update');

        Route::get('profile/update', 'Dashboard\ProfileController@edit')
            ->name('profile.edit');

        Route::put('profile/update', 'Dashboard\ProfileController@update')
            ->name('profile.update');
    });


    Route::resource('users', 'Dashboard\UserController')
        ->except(['show', 'destroy'])
        ->middleware('can:manage,App\Models\User');

    Route::resource('coupons', 'Dashboard\CouponController')
        ->except(['show'])
        ->middleware('can:manage,App\Models\Coupon');

    Route::prefix('courses/{course}')->group(function () {
        Route::resource('chapters', 'Dashboard\ChapterController')
            ->except(['create', 'edit', 'show']);
        Route::resource('chapters/{chapter}/lessons', 'Dashboard\LessonController')
            ->only(['create', 'edit', 'store', 'update']);
    });

    Route::resource('courses', 'Dashboard\CourseController')
        ->except(['destroy']);

    Route::get('enrollments/pending', 'Dashboard\EnrollmentController@getPending')
        ->name('enrollments.pending');

    Route::post('enrollments/{id}/purchase/approve', 'Dashboard\PurchaseController@approve')
        ->name('enrollments.purchase.approve');

    Route::post('enrollments/{id}/purchase/deny', 'Dashboard\PurchaseController@deny')
        ->name('enrollments.purchase.deny');

    Route::get('enrollments', 'Dashboard\EnrollmentController@index')
        ->name('enrollments.index');

    Route::get('feedbacks/pending', 'Dashboard\FeedbackController@getPending')
        ->name('feedbacks.pending');

    Route::patch('feedbacks/{feedback}/approve', 'Dashboard\FeedbackController@approve')
        ->name('feedbacks.approve');

    Route::get('feedbacks', 'Dashboard\FeedbackController@index')
        ->name('feedbacks.index');

    Route::get('my/courses/ongoing', 'Dashboard\CourseController@getOnGoings')
        ->name('student.courses.ongoing');

    Route::get('my/courses/finished', 'Dashboard\CourseController@getFinished')
        ->name('student.courses.finished');
    
    Route::get('my/courses/{course}', 'Dashboard\CourseController@show')
        ->name('student.course.show');

    Route::prefix('my/courses/{course}')->group(function () {
        Route::post('enroll', 'Dashboard\EnrollmentController@store')
            ->name('student.course.enroll');

        Route::get('lessons/{order?}', 'Dashboard\LessonController@show')
            ->name('student.course.lesson.show');

        Route::get('purchase', 'Dashboard\PurchaseController@create')
            ->name('student.course.purchase.create');

        Route::post('purchase', 'Dashboard\PurchaseController@store')
            ->name('student.course.purchase.store');

        Route::get('purchase-success', 'Dashboard\PurchaseController@getSuccess')
            ->name('student.course.purchase.success');

        Route::get('coupon-check', 'Dashboard\CouponController@check')
            ->name('student.course.coupon.check');
        
        Route::patch('finish', 'Dashboard\EnrollmentController@markFinished')
            ->name('student.course.finish');

        Route::get('feedback', 'Dashboard\FeedbackController@create')
            ->name('student.course.feedback.create');

        Route::post('feedback', 'Dashboard\FeedbackController@store')
            ->name('student.course.feedback.store');

        Route::get('feedback/{feedback}/edit', 'Dashboard\FeedbackController@edit')
            ->name('student.course.feedback.edit');

        Route::put('feedback/{feedback}/update', 'Dashboard\FeedbackController@update')
            ->name('student.course.feedback.update');
    });

    Route::prefix('mail')->group(function () {
        Route::post('enrollment/{enrollment}/approve', 'Dashboard\MailController@sendPurchaseApprove')
            ->name('mail.send.purchase.approve');
        
        Route::post('enrollment/{enrollment}/decline', 'Dashboard\MailController@sendPurchaseDecline')
            ->name('mail.send.purchase.decline');
    });
});

Route::get('storage_link_hidden_url', function () {
    Artisan::call('storage:link');
});

app/Http/Controllers/Dashboard/ChapterController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ChapterRequest;
use App\Models\Chapter;
use App\Models\Course;

class ChapterController extends Controller
{
    public function index(Course $course)
    {
        $this->authorize('manageChapter', $course);

        $chapters = Chapter::with(['lessons'])
            ->where('course_id', $course->id)
            ->orderBy('order', 'asc')
            ->get();

        return view('dashboard.pages.chapter.index', compact('course', 'chapters'));
    }

    public function store(ChapterRequest $request, Course $course)
    {
        $this->authorize('manageChapter', $course);

        Chapter::create($request->validated());

        return redirect()->back()->with('success', 'Chapter created successfully');
    }

    public function update(ChapterRequest $request, Course $course, Chapter $chapter)
    {
        $this->authorize('manageChapter', $course);
        
        $chapter->update($request->validated());

        return redirect()->back()->with('success', 'Chapter edited successfully');
    }
}

app/Http/Controllers/Dashboard/CouponController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Extensions\Formatter;
use App\Http\Controllers\Controller;
use App\Http\Requests\CouponRequest;
use App\Http\Services\CouponService;
use App\Models\Coupon;
use App\Models\Course;
use App\Models\User;
use Exception;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class CouponController extends Controller
{
    /** @var CouponService $couponService */
    private $couponService;

    public function __construct(CouponService $couponService)
    {
        $this->couponService = $couponService;
    }
    
    public function index()
    {
        $coupons = Coupon::paginate(Coupon::PAGINATION_LENGTH);

        return view('dashboard.pages.coupon.index', compact('coupons'));
    }

    public function create()
    {
        $courses = Course::all();
        $users = User::students()->get();

        return view('dashboard.pages.coupon.create', compact('courses', 'users'));
    }

    public function store(CouponRequest $request)
    {
        Coupon::create($request->validated());

        return redirect()->back()->with('success', 'Coupon created successfully');
    }

    public function edit(Coupon $coupon)
    {
        $courses = Course::all();
        $users = User::students()->get();

        return view('dashboard.pages.coupon.edit', compact('courses', 'users', 'coupon'));
    }

    public function update(CouponRequest $request, Coupon $coupon)
    {
        $coupon->update($request->validated());

        return redirect()->back()->with('success', 'Coupon updated successfully');
    }

    public function destroy(Coupon $coupon)
    {
        $coupon->delete();

        return response()->json([
            'status' => 'Coupon deleted successfully!'
        ]);
    }

    public function check(Request $request, Course $course)
    {
        $this->authorize('check', Coupon::class);

        $couponCode = $request->query('coupon');

        try {
            $coupon = $this->couponService->getByCode(
                $course,
                auth()->user(),
                $couponCode
            );
        } catch (Exception $e) {
            return response()->json([
                'status' => $e->getMessage()
            ], Response::HTTP_NOT_FOUND);
        }

        $discountedPrice = $this->couponService->getDiscountedPrice($course, $coupon);

        if ($discountedPrice === 0) {
            $message = trans('dashboard.purchase.no_transaction_fee');
        } else {
            $message = trans('dashboard.purchase.transaction_instruction', [
                'amount' => Formatter::addCurrencyString($discountedPrice),
                'bkash_number' => $course->getBkashNumber()
            ]);
        }

        return response()->json([
            'status' => 'success',
            'coupon' => $couponCode,
            'message' => $message
        ]);
    }
}

app/Http/Controllers/Dashboard/CourseController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Exception;
use App\Models\User;
use App\Models\Course;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateCourseRequest;
use App\Http\Requests\UpdateCourseRequest;
use App\Http\Services\EnrollmentService;
use App\Http\Services\CourseService;
use App\Models\Feedback;
use App\Policies\FeedbackPolicy;
use Illuminate\View\View;

class CourseController extends Controller
{
    /** @var CourseService */
    private $courseService;

    /** @var EnrollmentService */
    private $enrollmentService;

    public function __construct(CourseService $courseService, EnrollmentService $enrollmentService)
    {
        $this->courseService = $courseService;
        $this->enrollmentService = $enrollmentService;
    }

    public function create()
    {
        $this->authorize('create', Course::class);

        return view('dashboard.pages.course.create');
    }

    public function store(CreateCourseRequest $request)
    {
        $this->authorize('create', Course::class);

        $this->courseService->create($request->validated());

        return redirect()->back()->with('success', 'Course created successfully');
    }

    public function edit(Course $course)
    {
        $this->authorize('update', $course);

        return view('dashboard.pages.course.edit', compact('course'));
    }

    public function update(UpdateCourseRequest $request, Course $course)
    {
        $this->authorize('update', $course);

        $this->courseService->update($course, $request->validated());

        return redirect()->back()->with('success', 'Course edited successfully');
    }

    public function index()
    {
        $this->authorize('viewAny', Course::class);

        $courses = [];
        
        /** @var User $loggedInUser */
        $loggedInUser = auth()->user();

        if ($loggedInUser->isAdmin()) {
            $courses = $this->courseService->getAllForAdmin();
        } elseif ($loggedInUser->isInstructor()) {
            $courses = $this->courseService->getAllForInstructor(auth()->user()->id);
        }

        return view('dashboard.pages.course.index', compact('courses'));
    }

    public function show(Course $course)
    {
        $course->load(['instructor', 'chapters.lessons']);
        
        try {
            $enrollment = null;
            $feedback = null;

            /** @var User $loggedInUser */
            $loggedInUser = auth()->user();

            if ($loggedInUser->isStudent()) {
                $enrollment = $this->enrollmentService->getEnrollment(
                    $course->id,
                    auth()->user()->id,
                    ['course']
                );
                $feedback = Feedback::where('user_id', auth()->user()->id)
                    ->where('course_id', $course->id)
                    ->first();
            }

            $this->authorize('view', [$course, $enrollment]);
        } catch (Exception $e) {
            return redirect()->to('dashboard')->with('error', $e->getMessage());
        }

        return view('dashboard.pages.course.home', compact('course', 'enrollment', 'feedback'));
    }

    public function getOnGoings(): View
    {
        $this->authorize('viewOnGoing', Course::class);

        $onGoingCourses = $this->courseService->getOngoingCoursesForStudent(auth()->user()->id);

        return view('dashboard.pages.course.ongoing', compact('onGoingCourses'));
    }

    public function getFinished(): View
    {
        $this->authorize('viewFinished', Course::class);

        $finishedCourses = $this->courseService->getFinishedCoursesForStudent(auth()->user()->id);

        return view('dashboard.pages.course.finished', compact('finishedCourses'));
    }
}

app/Http/Controllers/Dashboard/EnrollmentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Services\EnrollmentService;
use Illuminate\Http\RedirectResponse;
use App\Http\Services\CourseService;
use App\Models\Course;
use App\Models\Enrollment;

class EnrollmentController extends Controller
{
    /** @var EnrollmentService */
    protected $enrollmentService;

    /** @var CourseService  */
    private $courseService;

    public function __construct(
        EnrollmentService $enrollmentService,
        CourseService $courseService
    ) {
        $this->enrollmentService = $enrollmentService;
        $this->courseService = $courseService;
    }

    /**
     * @param Course $course
     * @return RedirectResponse
     * @throws Exception
     */
    public function store(Course $course): RedirectResponse
    {
        $this->authorize('create', Enrollment::class);

        if ($course->isNotAvailable()) {
            return redirect()->back()
                ->with('error', 'Sorry, the course is not available');
        }

        $enrollment = $this->enrollmentService->getEnrollment($course->id, auth()->user()->id);

        if ($enrollment) {
            session()->flash('error', 'You have already enrolled to the course');
        } else {
            $this->enrollmentService->createEnrollment($course, auth()->user()->id);
            
            session()->flash('success', 'Thanks for joining the course');
        }

        return redirect()
            ->route('student.course.show', $course);
    }

    public function index()
    {
        $this->authorize('viewAny', Enrollment::class);

        $enrollments = $this->enrollmentService->getPaginated();

        return view('dashboard.pages.enrollment.index', compact('enrollments'));
    }

    public function getPending()
    {
        $this->authorize('viewPending', Enrollment::class);

        $enrollments = $this->enrollmentService->getPendingEnrollments();

        return view('dashboard.pages.enrollment.pending-approval', compact('enrollments'));
    }

    public function markFinished(Course $course)
    {
        $enrollment = $this->enrollmentService->getEnrollment(
            $course->id,
            auth()->user()->id
        );
        
        $this->authorize('markFinished', [$course, $enrollment]);

        $enrollment->update([
            'is_finished' => true
        ]);
        
        return redirect()->route('student.course.feedback.create', $course);
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Services\DashboardService;
use App\Models\User;

class HomeController extends Controller
{
    /** @var DashboardService  */
    private $dashboardService;

    public function __construct(DashboardService $dashboardService)
    {
        $this->dashboardService = $dashboardService;
    }

    public function __invoke()
    {
        /** @var User $loggedInUser */
        $loggedInUser = auth()->user();

        if ($loggedInUser->isStudent()) {
            $viewData = $this->dashboardService->getDataForStudent();

            return view('dashboard.pages.home.student', $viewData);
        } elseif ($loggedInUser->isInstructor()) {
            //TODO implement the logic for instructor
            $viewData = [];

            return view('dashboard.pages.home.instructor', $viewData);
        } elseif ($loggedInUser->isAdmin()) {
            //TODO implement the logic for Admin
            $viewData = [];

            return view('dashboard.pages.home.admin', $viewData);
        }

        abort(404, 'Invalid user role');
    }
}

resources/views/dashboard/layouts/course-contents-sidebar.blade.php
<div class="nk-sidebar">
    <div class="nk-nav-scroll">
        <ul class="metismenu" id="menu">
            <li>
                <a class="font-weight-bold" href="{{route('student.course.show', $course)}}" aria-expanded="false">
                    <i class="icon-notebook menu-icon"></i>
                    <span class="nav-text">{{$course->title}}</span>
                </a>
            </li>
            <li class="nav-label">{{__('dashboard.course.chapters')}}</li>

            @foreach($course->chapters as $chapter)
                <li>
                    <a class="has-arrow" href="javascript:void();" aria-expanded="false">
                        <i class="icon-book-open menu-icon"></i>
                        <span class="nav-text">{{ $chapter->title }}</span>
                    </a>
                    <ul aria-expanded="false">
                        @foreach($chapter->lessons as $lesson)
                            <li>
                                @can('view', [$lesson, $course, $enrollment])
                                <a href="{{route('student.course.lesson.show', [$course, $lesson->order])}}">
                                    {{$lesson->title}}
                                </a>
                                @endcan
                                @cannot('view', [$lesson, $course, $enrollment])
                                    <a href="javascript:void();"
                                       class="disabled"
                                       data-toggle="tooltip"
                                       data-placement="top"
                                        title="" data-original-title="{{__('dashboard.course.buy_to_view')}}">
                                        <i class="icon-lock"></i> {{$lesson->title}}
                                    </a>
                                @endcannot
                            </li>
                        @endforeach
                    </ul>
                </li>
            @endforeach
        </ul>
    </div>
</div>

resources/views/dashboard/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Megaminds: @yield('page_title')</title>

        <!-- Favicon icon -->
        <link rel="icon" type="image/png" sizes="16x16" href="{{asset('favicon.png')}}">

        @include('dashboard.layouts.common.styles')
        @yield('styles')
    </head>

    <body>

        @include('dashboard.layouts.common.preloader')

        <div id="main-wrapper">

            @include('dashboard.layouts.common.header')

            @yield('sidebar')

            <div class="content-body">

                @yield('breadcrumb')

                <div class="container-fluid">
                    @include('dashboard.components.flash-message')

                    @yield('content')
                </div>
            </div>

            @include('dashboard.layouts.common.footer')
        </div>

        @include('dashboard.layouts.common.scripts')
        @yield('scripts')
    </body>
</html>

resources/views/dashboard/layouts/sidebar.blade.php
<div class="nk-sidebar">
    <div class="nk-nav-scroll">
        <ul class="metismenu" id="menu">
            <li>
                <a href="{{route('dashboard')}}" aria-expanded="false">
                    <i class="icon-home menu-icon"></i><span class="nav-text">{{__('dashboard.sidebar.dashboard')}}</span>
                </a>
            </li>

            @can('manage', App\Models\User::class)
                <li>
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                        <i class="icon-tag menu-icon"></i><span class="nav-text">{{__('dashboard.sidebar.users')}}</span>
                    </a>
                    <ul aria-expanded="false">
                        <li><a href="{{ route('users.index') }}">{{__('dashboard.sidebar.user_list')}}</a></li>
                        <li><a href="{{ route('users.create') }}">{{__('dashboard.sidebar.create_new_user')}}</a></li>
                    </ul>
                </li>
            @endcan

            @if(auth()->user()->isStudent())
                <li>
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                        <i class="icon-book-open menu-icon"></i><span class="nav-text">{{__('dashboard.sidebar.my_courses')}}</span>
                    </a>
                    <ul aria-expanded="false">
                        <li><a href="{{ route('student.courses.ongoing') }}">{{__('dashboard.sidebar.ongoing_courses')}}</a></li>
                        <li><a href="{{ route('student.courses.finished') }}">{{__('dashboard.sidebar.finished_courses')}}</a></li>
                    </ul>
                </li>
            @endif

            @canany(['viewAny', 'create'], App\Models\Course::class)
                <li>
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                        <i class="icon-book-open menu-icon"></i><span class="nav-text">{{__('dashboard.sidebar.courses')}}</span>
                    </a>
                    <ul aria-expanded="false">
                        @can('viewAny', App\Models\Course::class)
                            <li><a href="{{ route('courses.index') }}">{{__('dashboard.sidebar.course_list')}}</a></li>
                        @endcan
                        
                        @can('create', App\Models\Course::class)
                            <li><a href="{{ route('courses.create') }}">{{__('dashboard.sidebar.create_new_course')}}</a></li>
                        @endcan
                    </ul>
                </li>
            @endcanany

            @can('manage', App\Models\Coupon::class)
                <li>
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                        <i class="icon-tag menu-icon"></i><span class="nav-text">{{__('dashboard.sidebar.coupons')}}</span>
                    </a>
                    <ul aria-expanded="false">
                        <li><a href="{{ route('coupons.index') }}">{{__('dashboard.sidebar.coupon_list')}}</a></li>
                        <li><a href="{{ route('coupons.create') }}">{{__('dashboard.sidebar.create_new_coupon')}}</a></li>
                    </ul>
                </li>
            @endcan

            @canany(['viewAny', 'viewPending'], App\Models\Enrollment::class)
                <li>
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                        <i class="icon-notebook menu-icon"></i><span class="nav-text">{{__('dashboard.sidebar.enrollments')}}</span>
                    </a>
                    <ul aria-expanded="false">
                        @can('viewAny', App\Models\Enrollment::class)
                            <li><a href="{{ route('enrollments.index') }}">{{__('dashboard.sidebar.enrollment_list')}}</a></li>
                        @endcan
                        @can('viewPending', App\Models\Enrollment::class)
                        <li><a href="{{ route('enrollments.pending') }}">{{__('dashboard.sidebar.pending_enrollments')}}</a></li>
                        @endcan
                    </ul>
                </li>
            @endcanany

            @canany(['viewAny', 'viewPending'], App\Models\Feedback::class)
                <li>
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                        <i class="icon-envelope menu-icon"></i><span class="nav-text">{{__('dashboard.sidebar.feedbacks')}}</span>
                    </a>
                    <ul aria-expanded="false">
                        @can('viewAny', App\Models\Feedback::class)
                            <li><a href="{{ route('feedbacks.index') }}">{{__('dashboard.sidebar.feedback_list')}}</a></li>
                        @endcan
                        @can('viewPending', App\Models\Feedback::class)
                        <li><a href="{{ route('feedbacks.pending') }}">{{__('dashboard.sidebar.pending_feedbacks')}}</a></li>
                        @endcan
                    </ul>
                </li>
            @endcanany
        </ul>
    </div>
</div>